@extends('layouts.app-2')

@section('page-title', 'Detail Prestasi - Ruang BK')

@section('body')
@php $tone = match($achievement->verificationStatus->code) {'terverifikasi' => 'success', 'ditolak' => 'danger', default => 'warning'}; @endphp
<div class="sibk-dashboard">
    <div class="sibk-page-header d-flex flex-wrap justify-content-between gap-3 mb-4"><div class="sibk-page-header__copy"><a href="{{ route('achievements.index') }}" class="text-decoration-none small">&larr; Daftar Prestasi</a><h1>Detail Prestasi</h1><p>Data, bukti metadata, dan hasil verifikasi prestasi.</p></div><div class="d-flex gap-2">@if(auth()->user()?->hasRole('guru_bk') && $achievement->verificationStatus->code === 'terverifikasi')<a href="{{ route('corrections.create', ['target_type' => 'achievement', 'target_id' => $achievement->id]) }}" class="btn btn-outline-secondary">Ajukan Koreksi</a>@endif @if($canUpdateAchievement)<a href="{{ route('achievements.edit', $achievement) }}" class="btn btn-primary">Edit Prestasi</a>@endif</div></div>
    <div class="row g-4"><div class="col-12 col-lg-8"><div class="sibk-panel h-100"><div class="sibk-panel__body p-4"><div class="d-flex flex-wrap justify-content-between gap-3 mb-4"><div><h2 class="fs-4 mb-1">{{ $achievement->activity_name }}</h2><p class="text-muted mb-0">{{ $achievement->student->name }} — {{ $achievement->student->nisn }}</p></div><span class="badge text-bg-{{ $tone }} align-self-start">{{ $achievement->verificationStatus->label }}</span></div><dl class="row mb-0"><dt class="col-sm-4">Jenis / Tingkat</dt><dd class="col-sm-8">{{ $achievement->type->label }} / {{ $achievement->level->label }}</dd><dt class="col-sm-4">Penyelenggara</dt><dd class="col-sm-8">{{ $achievement->organizer }}</dd><dt class="col-sm-4">Tanggal</dt><dd class="col-sm-8">{{ $achievement->achievement_date->locale('id')->translatedFormat('d F Y') }}</dd><dt class="col-sm-4">Hasil</dt><dd class="col-sm-8">{{ $achievement->result }}</dd><dt class="col-sm-4">Referensi Bukti</dt><dd class="col-sm-8">@if($evidenceUrl)<a href="{{ $evidenceUrl }}" target="_blank" rel="noopener noreferrer">{{ $achievement->evidence_reference }}</a>@else{{ $achievement->evidence_reference }}@endif</dd><dt class="col-sm-4">Keterangan Bukti</dt><dd class="col-sm-8">{{ $achievement->evidence_description ?: '—' }}</dd><dt class="col-sm-4">Catatan</dt><dd class="col-sm-8">{{ $achievement->notes ?: '—' }}</dd></dl></div></div></div>
        <div class="col-12 col-lg-4"><div class="sibk-panel mb-4"><div class="sibk-panel__body p-4"><h2 class="fs-5">Pemeriksaan</h2><p class="mb-1"><span class="text-muted small d-block">Pencatat</span>{{ $achievement->recorder->name }}</p><p class="mb-1"><span class="text-muted small d-block">Pemeriksa</span>{{ $achievement->reviewer?->name ?? 'Belum diperiksa' }}</p><p class="mb-1"><span class="text-muted small d-block">Waktu pemeriksaan</span>{{ $achievement->reviewed_at?->locale('id')->translatedFormat('d M Y H.i') ?? '—' }}</p><p class="mb-0"><span class="text-muted small d-block">Catatan pemeriksaan</span>{{ $achievement->verification_notes ?: '—' }}</p></div></div>
        @if($canVerifyAchievement)<div class="sibk-panel"><div class="sibk-panel__body p-4"><h2 class="fs-5">Verifikasi Prestasi</h2><form action="{{ route('achievements.verify', $achievement) }}" method="POST">@csrf<div class="mb-3"><label for="decision" class="form-label">Keputusan</label><select id="decision" name="decision" class="form-select" required><option value="">Pilih keputusan</option><option value="terverifikasi" @selected(old('decision') === 'terverifikasi')>Terverifikasi</option><option value="ditolak" @selected(old('decision') === 'ditolak')>Ditolak</option></select></div><div class="mb-3"><label for="verification_notes" class="form-label">Catatan pemeriksaan</label><textarea id="verification_notes" name="verification_notes" class="form-control" rows="3">{{ old('verification_notes') }}</textarea><div class="form-text">Wajib diisi bila prestasi ditolak.</div></div><button class="btn btn-primary w-100">Simpan Keputusan</button></form></div></div>@endif</div></div>
</div>
@endsection
