@extends('layouts.app-2')
@section('page-title', 'Ajukan Koreksi Data - Ruang BK')
@section('body')
<div class="sibk-dashboard">
    <div class="sibk-page-header mb-4"><div class="d-flex align-items-center gap-3"><a href="{{ route('corrections.index') }}" class="btn btn-light" aria-label="Kembali">&larr;</a><div class="sibk-page-header__copy m-0"><h1>Ajukan Koreksi Data</h1><p>Usulkan perubahan operasional atau laporkan kesalahan data master secara resmi.</p></div></div></div>
    @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form action="{{ route('corrections.store') }}" method="POST">@csrf
        <div class="sibk-panel mb-4"><div class="sibk-panel__header p-4 pb-0"><h2 class="sibk-panel__title">Target Data yang Dikoreksi</h2></div><div class="sibk-panel__body p-4 row g-4">
            <div class="col-12 col-md-4"><label for="target_type" class="form-label fw-semibold">Kategori Objek <span class="text-danger">*</span></label><select class="form-select" id="target_type" name="target_type" required><option value="">Pilih kategori</option>@if($cases->isNotEmpty())<option value="case" @selected(old('target_type', $preselectedType) === 'case')>Kasus (Operasional)</option>@endif @if($followUps->isNotEmpty())<option value="follow_up" @selected(old('target_type', $preselectedType) === 'follow_up')>Tindak Lanjut (Operasional)</option>@endif @if($consultations->isNotEmpty())<option value="consultation" @selected(old('target_type', $preselectedType) === 'consultation')>Konsultasi (Operasional)</option>@endif <option value="student" @selected(old('target_type', $preselectedType) === 'student')>Murid (Master Dapodik)</option></select></div>
            <div class="col-12 col-md-8"><label for="target_id" class="form-label fw-semibold">Objek Target <span class="text-danger">*</span></label><select class="form-select" id="target_id" name="target_id" required><option value="">Pilih objek</option>@foreach($cases as $case)<option data-target-type="case" value="{{ $case->id }}" @selected(old('target_type', $preselectedType) === 'case' && (string) old('target_id', $preselectedId) === (string) $case->id)>Kasus {{ $case->registration_number }} — {{ $case->identityName() }}</option>@endforeach @foreach($followUps as $followUp)<option data-target-type="follow_up" value="{{ $followUp->id }}" @selected(old('target_type', $preselectedType) === 'follow_up' && (string) old('target_id', $preselectedId) === (string) $followUp->id)>Tindak lanjut {{ $followUp->case?->registration_number }} — {{ $followUp->planned_date->format('d-m-Y') }}</option>@endforeach @foreach($consultations as $consultation)<option data-target-type="consultation" value="{{ $consultation->id }}" @selected(old('target_type', $preselectedType) === 'consultation' && (string) old('target_id', $preselectedId) === (string) $consultation->id)>Konsultasi {{ $consultation->registration_number }} — {{ $consultation->identityName() }}</option>@endforeach @foreach($students as $student)<option data-target-type="student" value="{{ $student->id }}" @selected(old('target_type', $preselectedType) === 'student' && (string) old('target_id', $preselectedId) === (string) $student->id)>Murid {{ $student->name }} — {{ $student->nisn }}</option>@endforeach</select></div>
            <div class="col-12 col-md-6"><label for="field_name" class="form-label fw-semibold">Atribut / Field <span class="text-danger">*</span></label><select class="form-select" id="field_name" name="field_name" required><option value="">Pilih atribut</option>@foreach($fieldDefinitions as $type => $fields)@foreach($fields as $name => $definition)<option data-target-type="{{ $type }}" value="{{ $name }}" @selected(old('field_name') === $name && old('target_type', $preselectedType) === $type)>{{ $definition['label'] }}</option>@endforeach @endforeach</select></div>
            <div class="col-12 col-md-6"><label for="proposed_value" class="form-label fw-semibold">Nilai Usulan <span class="text-danger">*</span></label><input class="form-control" id="proposed_value" name="proposed_value" value="{{ old('proposed_value') }}" placeholder="Untuk referensi, isi kode atau label resmi"><div class="form-text">Nilai lama dibaca oleh server. Format tanggal: YYYY-MM-DD; jam: HH:MM.</div></div>
        </div></div>
        <div class="sibk-panel mb-4"><div class="sibk-panel__header p-4 pb-0"><h2 class="sibk-panel__title">Alasan Pengajuan</h2></div><div class="sibk-panel__body p-4"><textarea class="form-control" id="reason" name="reason" rows="4" required placeholder="Jelaskan dasar koreksi dan sumber pemeriksaan.">{{ old('reason') }}</textarea></div></div>
        <div class="alert alert-info"><strong>Ketentuan:</strong> koreksi operasional diverifikasi Koordinator BK. Koreksi master tidak mengubah Dapodik dari aplikasi dan hanya selesai setelah sinkronisasi resmi sesuai usulan.</div>
        <div class="d-flex justify-content-end gap-2 mb-5"><a href="{{ route('corrections.index') }}" class="btn btn-outline-secondary">Batal</a><button type="submit" class="btn btn-primary">Kirim Pengajuan Koreksi</button></div>
    </form>
</div>
@endsection
@section('extra-javascript')
<script>document.addEventListener('DOMContentLoaded',()=>{const type=document.getElementById('target_type');const target=document.getElementById('target_id');const field=document.getElementById('field_name');const filter=(select)=>{const selected=select.value;[...select.options].forEach((option)=>{if(!option.dataset.targetType)return;option.hidden=option.dataset.targetType!==type.value;option.disabled=option.hidden;});if(select.selectedOptions[0]?.disabled)select.value='';if(selected&&[...select.options].some((option)=>option.value===selected&&!option.disabled))select.value=selected;};const refresh=()=>{filter(target);filter(field);};type.addEventListener('change',refresh);refresh();});</script>
@endsection
