@extends('layouts.app-2')
@section('page-title', 'Detail Koreksi - Ruang BK')
@section('body')
<div class="sibk-dashboard" data-page-id="PG-405">
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="sibk-page-header mb-4"><a href="{{ route('corrections.index') }}" class="small text-decoration-none">&larr; Koreksi Data</a><div class="sibk-page-header__copy"><h1>Detail Koreksi</h1><p>{{ $correction->registration_number }}</p></div></div>
    <div class="sibk-panel mb-4"><div class="sibk-panel__header p-4 pb-0"><h2 class="sibk-panel__title">Informasi Pengajuan</h2></div><div class="sibk-panel__body p-4 row g-3"><div class="col-md-6"><span class="text-muted small d-block">Objek</span><strong>{{ $correction->target_label }}</strong></div><div class="col-md-3"><span class="text-muted small d-block">Jenis</span>{{ $correction->correction_type === 'master' ? 'Master' : 'Operasional' }}</div><div class="col-md-3"><span class="text-muted small d-block">Status</span><span class="sibk-badge sibk-badge--primary">{{ $correction->status->label }}</span></div><div class="col-md-6"><span class="text-muted small d-block">Atribut</span>{{ $correction->field_label }}</div><div class="col-md-3"><span class="text-muted small d-block">Pengaju</span>{{ $correction->requester->name }}</div><div class="col-md-3"><span class="text-muted small d-block">Waktu</span>{{ $correction->created_at->locale('id')->translatedFormat('d F Y H:i') }}</div></div></div>
    <div class="sibk-panel mb-4"><div class="sibk-panel__header p-4 pb-0"><h2 class="sibk-panel__title">Perbandingan Nilai</h2></div><div class="sibk-panel__body p-4"><div class="row g-3 mb-3"><div class="col-md-6"><div class="p-3 rounded border bg-light"><span class="text-muted small">Nilai Lama</span><div class="fw-bold fs-5 text-break">{{ $correction->old_value_label ?? 'Kosong' }}</div></div></div><div class="col-md-6"><div class="p-3 rounded border border-primary bg-primary-subtle"><span class="text-primary small">Nilai Usulan</span><div class="fw-bold fs-5 text-primary text-break">{{ $correction->proposed_value_label ?? 'Kosong' }}</div></div></div></div><strong>Alasan Pengajuan</strong><p class="mb-0 text-break">{{ $correction->reason }}</p></div></div>
    @if($correction->reviewer)<div class="sibk-panel mb-4"><div class="sibk-panel__header p-4 pb-0"><h2 class="sibk-panel__title">Hasil Pemeriksaan</h2></div><div class="sibk-panel__body p-4"><p><span class="text-muted small d-block">Pemeriksa</span>{{ $correction->reviewer->name }} — {{ $correction->reviewed_at?->locale('id')->translatedFormat('d F Y H:i') }}</p><p class="mb-0"><span class="text-muted small d-block">Catatan</span>{{ $correction->review_notes ?: 'Tidak ada catatan.' }}</p>@if($correction->externalSyncRun)<p class="mt-3 mb-0"><span class="text-muted small d-block">Hasil sinkronisasi sumber</span>Dapodik #{{ $correction->externalSyncRun->id }} — {{ $correction->externalSyncRun->status }} — {{ $correction->externalSyncRun->finished_at?->locale('id')->translatedFormat('d F Y H:i') }}</p>@endif</div></div>@endif
    @if($canVerify)<form action="{{ route('corrections.verify', $correction) }}" method="POST" class="sibk-panel mb-4"><div class="sibk-panel__header p-4 pb-0"><h2 class="sibk-panel__title">Verifikasi Koordinator BK</h2></div><div class="sibk-panel__body p-4 row g-3">@csrf<div class="col-md-5"><label for="decision" class="form-label">Keputusan</label><select class="form-select" id="decision" name="decision" required><option value="">Pilih keputusan</option><option value="approved">Setujui dan Terapkan</option><option value="rejected">Tolak</option><option value="revision_requested">Minta Perbaikan</option></select></div><div class="col-12"><label for="review_notes" class="form-label">Catatan Pemeriksaan</label><textarea class="form-control" id="review_notes" name="review_notes" rows="3">{{ old('review_notes') }}</textarea></div><div class="col-12 text-end"><button class="btn btn-primary">Simpan Keputusan</button></div></div></form>@endif
    @if($canProcessMaster)<form action="{{ route('corrections.process-master', $correction) }}" method="POST" class="sibk-panel mb-4"><div class="sibk-panel__header p-4 pb-0"><h2 class="sibk-panel__title">Pemrosesan Sumber Resmi oleh Admin IT</h2></div><div class="sibk-panel__body p-4 row g-3">@csrf<div class="col-md-5"><label for="action" class="form-label">Tindakan</label><select class="form-select" id="action" name="action" required><option value="processing">Tandai sedang diproses</option><option value="completed">Selesai setelah sinkronisasi</option><option value="rejected">Tolak laporan</option></select></div><div class="col-md-7"><label for="external_sync_run_id" class="form-label">Hasil Sinkronisasi Dapodik</label><select class="form-select" id="external_sync_run_id" name="external_sync_run_id"><option value="">Pilih saat menyelesaikan</option>@foreach($syncRuns as $run)<option value="{{ $run->id }}">#{{ $run->id }} — {{ $run->finished_at->format('d-m-Y H:i') }} — {{ $run->status }}</option>@endforeach</select></div><div class="col-12"><label for="master_review_notes" class="form-label">Catatan Pemrosesan</label><textarea class="form-control" id="master_review_notes" name="review_notes" rows="3">{{ old('review_notes') }}</textarea></div><div class="col-12 text-end"><button class="btn btn-primary">Simpan Status</button></div></div></form>@endif
</div>
@endsection
