<?php $__env->startSection('page-title', 'Layanan BK - Ruang BK'); ?>

<?php $__env->startSection('body'); ?>
    <div class="sibk-dashboard" data-page-id="PG-101">
        <?php if(session('success')): ?><div class="alert alert-success"><?php echo e(session('success')); ?></div><?php endif; ?>
        <div class="sibk-page-header d-flex flex-column flex-md-row align-items-md-center justify-content-between gap-3 mb-4">
            <div class="sibk-page-header__copy"><h1>Layanan BK</h1><p>Cari, filter, dan kelola penanganan kasus serta sesi konsultasi.</p></div>
            <?php if($activeTab === 'konsultasi' && $canCreateConsultation): ?><a href="<?php echo e(route('consultations.create')); ?>" class="btn btn-primary">Catat Konsultasi</a><?php elseif($activeTab === 'kasus' && $canCreateCase): ?><a href="<?php echo e(route('cases.create')); ?>" class="btn btn-primary">Buat Kasus Baru</a><?php endif; ?>
        </div>

        <ul class="nav nav-pills mb-4 gap-2">
            <li class="nav-item"><a class="nav-link <?php echo e($activeTab === 'kasus' ? 'active' : ''); ?>" href="<?php echo e(route('cases.index', ['tab' => 'kasus'])); ?>">Kasus & Penanganan</a></li>
            <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('viewAny', \App\Models\Consultation::class)): ?><li class="nav-item"><a class="nav-link <?php echo e($activeTab === 'konsultasi' ? 'active' : ''); ?>" href="<?php echo e(route('cases.index', ['tab' => 'konsultasi'])); ?>">Sesi Bimbingan & Konsultasi</a></li><?php endif; ?>
        </ul>

        <?php if($activeTab === 'kasus'): ?>
            <div class="sibk-panel mb-4"><div class="sibk-panel__body p-4"><form class="row g-3 align-items-end" action="<?php echo e(route('cases.index')); ?>" method="GET">
                <input type="hidden" name="tab" value="kasus">
                <div class="col-12 col-md-3"><label class="form-label" for="case_search">Cari kasus</label><input class="form-control" id="case_search" name="search" value="<?php echo e(request('search')); ?>" placeholder="Nomor kasus atau nama murid"></div>
                <div class="col-12 col-md-2"><label class="form-label" for="case_class">Kelas</label><select class="form-select" id="case_class" name="classroom_id"><option value="">Semua kelas</option><?php $__currentLoopData = $classrooms; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $classroom): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($classroom->id); ?>" <?php if((string) request('classroom_id') === (string) $classroom->id): echo 'selected'; endif; ?>><?php echo e($classroom->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
                <div class="col-12 col-md-2"><label class="form-label" for="case_source">Sumber</label><select class="form-select" id="case_source" name="case_source_id"><option value="">Semua sumber</option><?php $__currentLoopData = $caseSources; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $source): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($source->id); ?>" <?php if((string) request('case_source_id') === (string) $source->id): echo 'selected'; endif; ?>><?php echo e($source->label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
                <div class="col-12 col-md-2"><label class="form-label" for="case_status">Status</label><select class="form-select" id="case_status" name="status_id"><option value="">Semua status</option><?php $__currentLoopData = $caseStatuses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $status): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($status->id); ?>" <?php if((string) request('status_id') === (string) $status->id): echo 'selected'; endif; ?>><?php echo e($status->label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
                <div class="col-12 col-md-2"><label class="form-label" for="case_month">Periode</label><input type="month" class="form-control" id="case_month" name="month" value="<?php echo e(request('month')); ?>"></div>
                <div class="col-12 col-md-1"><button class="btn btn-outline-primary w-100">Filter</button></div>
            </form></div></div>
            <div class="table-responsive"><table class="table sibk-table mb-0"><thead><tr><th>No. Kasus</th><th>Murid</th><th>Kelas</th><th>Sumber</th><th>Bidang</th><th>Status</th><th>Tindak Lanjut</th><th></th></tr></thead><tbody>
                <?php $__empty_1 = true; $__currentLoopData = $cases; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $case): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
                    <?php $membership = $case->student?->classMemberships->sortByDesc('effective_from')->first(); $next = $case->followUps->first(fn ($item) => $item->planned_date->gte(today()) && $item->status?->code !== 'dibatalkan'); ?>
                    <tr><td class="fw-bold text-primary"><?php echo e($case->registration_number); ?></td><td class="fw-semibold"><?php echo e($case->identityName()); ?><?php if($case->temporary_student_id): ?> <span class="badge bg-warning-subtle text-warning-emphasis">Sementara</span><?php endif; ?></td><td><?php echo e($membership?->classroom?->name ?? '—'); ?></td><td><?php echo e($case->source->label); ?></td><td><?php echo e($case->serviceField->label); ?></td><td><span class="sibk-badge sibk-badge--primary"><?php echo e($case->status->label); ?></span></td><td><?php echo e($next?->planned_date?->locale('id')->translatedFormat('d M Y') ?? '—'); ?></td><td><a href="<?php echo e(route('cases.show', $case)); ?>" class="fw-bold text-decoration-none">Buka</a></td></tr>
                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="8" class="text-center text-muted py-4">Belum ada kasus yang dapat Anda akses.</td></tr><?php endif; ?>
            </tbody></table></div><?php if($cases->hasPages()): ?><div class="mt-3"><?php echo e($cases->links()); ?></div><?php endif; ?>
        <?php else: ?>
            <div class="sibk-panel mb-4"><div class="sibk-panel__body p-4"><form class="row g-3 align-items-end" action="<?php echo e(route('cases.index')); ?>" method="GET">
                <input type="hidden" name="tab" value="konsultasi">
                <div class="col-12 col-lg-3"><label class="form-label" for="consultation_search">Cari sesi</label><input class="form-control" id="consultation_search" name="search" value="<?php echo e(request('search')); ?>" placeholder="Nomor, nama, NISN, atau topik"></div>
                <div class="col-6 col-lg-2"><label class="form-label" for="consultation_class">Kelas</label><select class="form-select" id="consultation_class" name="classroom_id"><option value="">Semua kelas</option><?php $__currentLoopData = $classrooms; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $classroom): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($classroom->id); ?>" <?php if((string) request('classroom_id') === (string) $classroom->id): echo 'selected'; endif; ?>><?php echo e($classroom->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
                <div class="col-6 col-lg-2"><label class="form-label" for="consultation_field">Jenis</label><select class="form-select" id="consultation_field" name="service_field_id"><option value="">Semua jenis</option><?php $__currentLoopData = $serviceFields; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $field): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($field->id); ?>" <?php if((string) request('service_field_id') === (string) $field->id): echo 'selected'; endif; ?>><?php echo e($field->label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
                <div class="col-6 col-lg-2"><label class="form-label" for="consultation_status">Status</label><select class="form-select" id="consultation_status" name="consultation_status_id"><option value="">Semua status</option><?php $__currentLoopData = $consultationStatuses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $status): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($status->id); ?>" <?php if((string) request('consultation_status_id') === (string) $status->id): echo 'selected'; endif; ?>><?php echo e($status->label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
                <div class="col-6 col-lg-2"><label class="form-label" for="consultation_month">Bulan</label><input type="month" class="form-control" id="consultation_month" name="month" value="<?php echo e(request('month')); ?>"></div>
                <div class="col-12 col-lg-1"><button class="btn btn-outline-primary w-100">Filter</button></div>
            </form></div></div>
            <div class="table-responsive"><table class="table sibk-table mb-0"><thead><tr><th>No. Sesi</th><th>Murid & Kelas</th><th>Topik & Jenis</th><th>Jadwal</th><th>Status</th><th>Guru BK</th><th></th></tr></thead><tbody>
                <?php $__empty_1 = true; $__currentLoopData = $consultations; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $session): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
                    <?php $membership = $session->student?->classMemberships->sortByDesc('effective_from')->first(); ?>
                    <tr><td class="fw-bold text-primary"><?php echo e($session->registration_number); ?></td><td><strong><?php echo e($session->identityName()); ?></strong><div class="small text-muted"><?php echo e($membership?->classroom?->name ?? ($session->temporary_student_id ? 'Identitas sementara' : '—')); ?></div></td><td><span class="fw-semibold"><?php echo e($session->topic); ?></span><div class="small text-muted"><?php echo e($session->serviceField->label); ?></div></td><td><?php echo e($session->session_date->locale('id')->translatedFormat('d M Y')); ?><?php if($session->starts_at): ?><div class="small text-muted"><?php echo e(substr($session->starts_at, 0, 5)); ?><?php if($session->ends_at): ?>–<?php echo e(substr($session->ends_at, 0, 5)); ?><?php endif; ?></div><?php endif; ?></td><td><span class="sibk-badge sibk-badge--primary"><?php echo e($session->status->label); ?></span></td><td><?php echo e($session->counselor->name); ?></td><td><a href="<?php echo e(route('consultations.show', $session)); ?>" class="fw-bold text-decoration-none">Buka</a></td></tr>
                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7" class="text-center text-muted py-4">Belum ada sesi konsultasi yang dapat Anda akses.</td></tr><?php endif; ?>
            </tbody></table></div><?php if($consultations->hasPages()): ?><div class="mt-3"><?php echo e($consultations->links()); ?></div><?php endif; ?>
        <?php endif; ?>
    </div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app-2', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\Tugas\pepe g\smt 2\pk\sibk\sibk\resources\views\pages\cases\index.blade.php ENDPATH**/ ?>