<?php $__env->startSection('page-title', ($isEdit ? 'Edit' : 'Catat').' Prestasi - Ruang BK'); ?>

<?php $__env->startSection('body'); ?>
<div class="sibk-dashboard" data-page-id="PG-203">
    <div class="sibk-page-header d-flex flex-column flex-md-row align-items-md-center justify-content-between gap-3 mb-4">
        <div class="d-flex align-items-center gap-3"><a href="<?php echo e($isEdit ? route('achievements.show', $achievement) : route('achievements.index')); ?>" class="btn btn-icon btn-light" aria-label="Kembali">&larr;</a><div class="sibk-page-header__copy m-0"><h1 class="mb-1"><?php echo e($isEdit ? 'Edit Prestasi' : 'Catat Prestasi'); ?></h1><p class="mb-0"><?php echo e($isEdit ? 'Perbarui prestasi yang masih menunggu verifikasi.' : 'Tambahkan riwayat prestasi murid sesuai kewenangan Anda.'); ?></p></div></div>
    </div>
    <?php if($errors->any()): ?><div class="alert alert-danger"><strong>Periksa kembali data berikut:</strong><ul class="mb-0 mt-2"><?php $__currentLoopData = $errors->all(); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $error): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><li><?php echo e($error); ?></li><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></ul></div><?php endif; ?>
    <form action="<?php echo e($isEdit ? route('achievements.update', $achievement) : route('achievements.store')); ?>" method="POST" class="d-flex flex-column gap-4">
        <?php echo csrf_field(); ?> <?php if($isEdit): ?> <?php echo method_field('PATCH'); ?> <?php endif; ?>
        <div class="sibk-panel"><div class="sibk-panel__body p-4 p-md-5"><h2 class="sibk-section-title mb-4">Informasi Prestasi</h2><div class="row g-3">
            <div class="col-12 col-md-6 col-lg-5"><label for="student_id" class="form-label sibk-form-label">Murid <span class="text-danger">*</span></label><?php if($isEdit): ?><input class="form-control" value="<?php echo e($achievement->student->name); ?> — <?php echo e($achievement->student->nisn); ?>" disabled><?php else: ?><select class="form-select sibk-form-select" id="student_id" name="student_id" required><option value="">Pilih murid</option><?php $__currentLoopData = $students; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $student): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php $membership = $student->classMemberships->first(); ?><option value="<?php echo e($student->id); ?>" <?php if((string) old('student_id', $preselectedStudentId) === (string) $student->id): echo 'selected'; endif; ?>><?php echo e($student->name); ?> — <?php echo e($student->nisn); ?><?php echo e($membership?->classroom ? ' · '.$membership->classroom->name : ''); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select><?php endif; ?></div>
            <div class="col-12 col-md-3 col-lg-4"><label for="type_id" class="form-label sibk-form-label">Jenis Prestasi <span class="text-danger">*</span></label><select class="form-select sibk-form-select" id="type_id" name="type_id" required><option value="">Pilih jenis prestasi</option><?php $__currentLoopData = $types; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $type): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($type->id); ?>" <?php if((string) old('type_id', $achievement?->type_id) === (string) $type->id): echo 'selected'; endif; ?>><?php echo e($type->label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
            <div class="col-12 col-md-3"><label for="level_id" class="form-label sibk-form-label">Tingkat <span class="text-danger">*</span></label><select class="form-select sibk-form-select" id="level_id" name="level_id" required><option value="">Pilih tingkat</option><?php $__currentLoopData = $levels; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $level): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($level->id); ?>" <?php if((string) old('level_id', $achievement?->level_id) === (string) $level->id): echo 'selected'; endif; ?>><?php echo e($level->label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
            <div class="col-12 col-md-5"><label for="activity_name" class="form-label sibk-form-label">Nama Kegiatan <span class="text-danger">*</span></label><input type="text" class="form-control sibk-form-control" id="activity_name" name="activity_name" maxlength="250" value="<?php echo e(old('activity_name', $achievement?->activity_name)); ?>" required></div>
            <div class="col-12 col-md-4"><label for="organizer" class="form-label sibk-form-label">Penyelenggara <span class="text-danger">*</span></label><input type="text" class="form-control sibk-form-control" id="organizer" name="organizer" maxlength="200" value="<?php echo e(old('organizer', $achievement?->organizer)); ?>" required></div>
            <div class="col-12 col-md-3"><label for="achievement_date" class="form-label sibk-form-label">Tanggal <span class="text-danger">*</span></label><input type="date" class="form-control sibk-form-control" id="achievement_date" name="achievement_date" max="<?php echo e(today()->toDateString()); ?>" value="<?php echo e(old('achievement_date', $achievement?->achievement_date?->toDateString())); ?>" required></div>
        </div></div></div>
        <div class="sibk-panel"><div class="sibk-panel__body p-4 p-md-5"><h2 class="sibk-section-title mb-4">Hasil dan Bukti</h2><div class="row g-3">
            <div class="col-12 col-md-6"><label for="result" class="form-label sibk-form-label">Hasil atau Peringkat <span class="text-danger">*</span></label><input type="text" class="form-control sibk-form-control" id="result" name="result" maxlength="250" value="<?php echo e(old('result', $achievement?->result)); ?>" required></div>
            <div class="col-12 col-md-6"><label class="form-label sibk-form-label">Status Verifikasi</label><input class="form-control" value="<?php echo e($achievement?->verificationStatus?->label ?? 'Menunggu Verifikasi'); ?>" disabled><div class="form-text">Status ditetapkan oleh Koordinator BK.</div></div>
            <div class="col-12"><label for="evidence_reference" class="form-label sibk-form-label">Referensi Bukti <span class="text-danger">*</span></label><input type="text" class="form-control sibk-form-control" id="evidence_reference" name="evidence_reference" maxlength="2000" value="<?php echo e(old('evidence_reference', $achievement?->evidence_reference)); ?>" placeholder="Tautan HTTP/HTTPS atau nomor/lokasi arsip" required><div class="form-text">Unggah berkas belum tersedia sampai aturan dokumen DEP-06 disahkan.</div></div>
            <div class="col-12"><label for="evidence_description" class="form-label sibk-form-label">Keterangan Bukti</label><textarea class="form-control sibk-form-control" id="evidence_description" name="evidence_description" rows="2"><?php echo e(old('evidence_description', $achievement?->evidence_description)); ?></textarea></div>
            <div class="col-12"><label for="notes" class="form-label sibk-form-label">Catatan</label><textarea class="form-control sibk-form-control" id="notes" name="notes" rows="3"><?php echo e(old('notes', $achievement?->notes)); ?></textarea></div>
        </div></div></div>
        <div class="d-flex justify-content-end gap-2 pb-4"><a href="<?php echo e($isEdit ? route('achievements.show', $achievement) : route('achievements.index')); ?>" class="btn btn-light">Batal</a><button type="submit" class="btn btn-primary"><?php echo e($isEdit ? 'Simpan Perubahan' : 'Simpan Prestasi'); ?></button></div>
    </form>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app-2', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\Tugas\pepe g\smt 2\pk\sibk\sibk\resources\views\pages\achievements\create.blade.php ENDPATH**/ ?>