<?php $__env->startSection('page-title', 'Notifikasi - Ruang BK'); ?>
<?php $__env->startSection('body'); ?>
<div class="container-fluid py-4 px-lg-4" data-page-id="PG-003">
    <?php if(session('success')): ?><div class="alert alert-success"><?php echo e(session('success')); ?></div><?php endif; ?>
    <div class="sibk-notification-header"><h1 class="sibk-page-title">Notifikasi</h1><p class="sibk-page-subtitle text-muted">Pemberitahuan operasional yang ditujukan khusus kepada Anda.</p></div>
    <div class="sibk-notification-tabs d-flex flex-wrap justify-content-between gap-2">
        <div class="d-flex gap-2"><a href="<?php echo e(route('notifications.preview')); ?>" class="btn <?php echo e($activeFilter === 'all' ? 'btn-primary' : 'btn-outline-secondary'); ?>">Semua</a><a href="<?php echo e(route('notifications.preview', ['filter' => 'unread'])); ?>" class="btn <?php echo e($activeFilter === 'unread' ? 'btn-primary' : 'btn-outline-secondary'); ?>">Belum dibaca <span class="badge bg-secondary ms-1"><?php echo e($unreadCount); ?></span></a></div>
        <?php if($unreadCount > 0): ?><form action="<?php echo e(route('notifications.read-all')); ?>" method="POST"><?php echo csrf_field(); ?><button class="btn btn-link text-decoration-none">Tandai semua dibaca</button></form><?php endif; ?>
    </div>
    <div class="sibk-panel"><div class="sibk-panel__header"><div class="sibk-panel__title-group"><h2>Daftar Notifikasi</h2><span class="badge bg-secondary ms-2"><?php echo e($notifications->total()); ?></span></div><form action="<?php echo e(route('notifications.preview')); ?>" method="GET" class="d-flex gap-2"><input type="hidden" name="filter" value="<?php echo e($activeFilter === 'unread' ? 'unread' : ''); ?>"><label class="visually-hidden" for="category">Kategori</label><select class="form-select form-select-sm" id="category" name="category"><option value="">Semua kategori</option><?php $__currentLoopData = ['schedule' => 'Jadwal', 'assignment' => 'Penugasan', 'coordination' => 'Koordinasi', 'correction' => 'Koreksi', 'change' => 'Perubahan']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $code => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($code); ?>" <?php if(request('category') === $code): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select><button class="btn btn-sm btn-outline-primary">Filter</button></form></div>
        <div class="sibk-notification-list"><?php $__empty_1 = true; $__currentLoopData = $notifications; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $notification): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><a href="<?php echo e(route('notifications.open', $notification)); ?>" class="sibk-notification-item <?php echo e($notification->read_at === null ? 'is-unread' : ''); ?>"><div class="sibk-notification-item__icon-col"><div class="sibk-notification-item__icon sibk-icon-tone--<?php echo e($notification->category === 'correction' ? 'warning' : ($notification->category === 'coordination' ? 'info' : 'primary')); ?>"><svg viewBox="0 0 24 24"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9ZM10 21h4"/></svg></div></div><div class="sibk-notification-item__content"><div class="sibk-notification-item__header"><p class="sibk-notification-item__title"><?php echo e($notification->title); ?></p><div class="sibk-notification-item__meta"><span class="sibk-notification-item__time"><?php echo e($notification->created_at->locale('id')->diffForHumans()); ?></span><?php if($notification->read_at === null): ?><span class="sibk-notification-item__unread-dot"></span><?php endif; ?></div></div><p class="sibk-notification-item__desc"><?php echo e($notification->message); ?></p></div></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="text-center py-5 text-muted"><p class="mb-0">Tidak ada notifikasi yang sesuai filter.</p></div><?php endif; ?></div>
        <?php if($notifications->hasPages()): ?><div class="sibk-panel__footer border-top px-4 py-3"><?php echo e($notifications->links()); ?></div><?php endif; ?>
    </div>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app-2', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\Tugas\pepe g\smt 2\pk\sibk\sibk\resources\views\pages\notifications\index.blade.php ENDPATH**/ ?>