<?php $__env->startSection('page-title', 'Daftar Prestasi - Ruang BK'); ?>

<?php $__env->startSection('body'); ?>
<div class="sibk-dashboard">
    <div class="sibk-page-header d-flex flex-wrap justify-content-between gap-3 mb-4"><div class="sibk-page-header__copy"><h1>Daftar Prestasi</h1><p>Riwayat dan antrean verifikasi sesuai kewenangan Anda.</p></div><?php if($canCreateAchievement): ?><a href="<?php echo e(route('achievements.create')); ?>" class="btn btn-primary">Catat Prestasi</a><?php endif; ?></div>
    <div class="sibk-panel mb-4"><div class="sibk-panel__body p-4"><form action="<?php echo e(route('achievements.index')); ?>" method="GET" class="row g-3 align-items-end">
        <div class="col-12 col-lg-4"><label for="achievement_search" class="form-label">Cari</label><input id="achievement_search" name="search" class="form-control" value="<?php echo e(request('search')); ?>" placeholder="Murid, NISN, kegiatan, atau penyelenggara"></div>
        <div class="col-6 col-md-3 col-lg-2"><label for="achievement_type" class="form-label">Jenis</label><select id="achievement_type" name="type_id" class="form-select"><option value="">Semua</option><?php $__currentLoopData = $types; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $type): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($type->id); ?>" <?php if((string) request('type_id') === (string) $type->id): echo 'selected'; endif; ?>><?php echo e($type->label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-6 col-md-3 col-lg-2"><label for="achievement_level" class="form-label">Tingkat</label><select id="achievement_level" name="level_id" class="form-select"><option value="">Semua</option><?php $__currentLoopData = $levels; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $level): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($level->id); ?>" <?php if((string) request('level_id') === (string) $level->id): echo 'selected'; endif; ?>><?php echo e($level->label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-6 col-md-3 col-lg-2"><label for="achievement_status" class="form-label">Status</label><select id="achievement_status" name="status_id" class="form-select"><option value="">Semua</option><?php $__currentLoopData = $statuses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $status): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($status->id); ?>" <?php if((string) request('status_id') === (string) $status->id): echo 'selected'; endif; ?>><?php echo e($status->label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-6 col-md-3 col-lg-2"><label for="achievement_class" class="form-label">Kelas historis</label><select id="achievement_class" name="classroom_id" class="form-select"><option value="">Semua</option><?php $__currentLoopData = $classrooms; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $classroom): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($classroom->id); ?>" <?php if((string) request('classroom_id') === (string) $classroom->id): echo 'selected'; endif; ?>><?php echo e($classroom->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-6 col-md-3"><label for="achievement_student" class="form-label">Murid</label><select id="achievement_student" name="student_id" class="form-select"><option value="">Semua</option><?php $__currentLoopData = $students; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $student): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($student->id); ?>" <?php if((string) request('student_id') === (string) $student->id): echo 'selected'; endif; ?>><?php echo e($student->name); ?> — <?php echo e($student->nisn); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-6 col-md-3"><label for="achievement_start" class="form-label">Tanggal awal</label><input type="date" id="achievement_start" name="date_start" class="form-control" value="<?php echo e(request('date_start')); ?>"></div>
        <div class="col-6 col-md-3"><label for="achievement_end" class="form-label">Tanggal akhir</label><input type="date" id="achievement_end" name="date_end" class="form-control" value="<?php echo e(request('date_end')); ?>"></div>
        <div class="col-12 col-md-3 d-flex gap-2"><button class="btn btn-primary flex-grow-1">Terapkan</button><a href="<?php echo e(route('achievements.index')); ?>" class="btn btn-light">Reset</a></div>
    </form></div></div>
    <div class="table-responsive"><table class="table sibk-table mb-0"><thead><tr><th>Murid</th><th>Kegiatan</th><th>Jenis / Tingkat</th><th>Tanggal</th><th>Hasil</th><th>Status</th><th></th></tr></thead><tbody>
        <?php $__empty_1 = true; $__currentLoopData = $achievements; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $achievement): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><?php $tone = match($achievement->verificationStatus->code) {'terverifikasi' => 'success', 'ditolak' => 'danger', default => 'warning'}; ?><tr><td><strong><?php echo e($achievement->student->name); ?></strong><span class="small text-muted d-block"><?php echo e($achievement->student->nisn); ?></span></td><td><?php echo e($achievement->activity_name); ?><span class="small text-muted d-block"><?php echo e($achievement->organizer); ?></span></td><td><?php echo e($achievement->type->label); ?><span class="small text-muted d-block"><?php echo e($achievement->level->label); ?></span></td><td><?php echo e($achievement->achievement_date->locale('id')->translatedFormat('d M Y')); ?></td><td><?php echo e($achievement->result); ?></td><td><span class="badge text-bg-<?php echo e($tone); ?>"><?php echo e($achievement->verificationStatus->label); ?></span></td><td><a href="<?php echo e(route('achievements.show', $achievement)); ?>">Buka</a></td></tr>
        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7" class="text-center text-muted py-5">Belum ada prestasi yang sesuai dengan filter dan kewenangan Anda.</td></tr><?php endif; ?>
    </tbody></table></div><?php if($achievements->hasPages()): ?><div class="mt-3"><?php echo e($achievements->links()); ?></div><?php endif; ?>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app-2', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\Tugas\pepe g\smt 2\pk\sibk\sibk\resources\views\pages\achievements\index.blade.php ENDPATH**/ ?>