<?php $__env->startSection('page-title', 'Profil Murid - Ruang BK'); ?>

<?php $__env->startSection('body'); ?>
    <?php
        $currentMembership = $memberships->first(fn ($membership) => $membership->is_active && $membership->effective_from->lte(today()) && ($membership->effective_until === null || $membership->effective_until->gte(today())));
        $initials = collect(explode(' ', $student->name))->filter()->take(2)->map(fn ($word) => mb_substr($word, 0, 1))->join('');
    ?>
    <div class="sibk-dashboard" data-page-id="PG-202">
        <div class="sibk-page-header d-flex flex-wrap justify-content-between gap-3 mb-4">
            <div class="sibk-page-header__copy"><a href="<?php echo e(route('students.index')); ?>" class="text-decoration-none small">&larr; Daftar Murid</a><h1>Profil Murid</h1><p>Riwayat layanan dan informasi terkait murid.</p></div>
            <div class="d-flex flex-wrap align-items-start gap-2">
                <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('create', \App\Models\Correction::class)): ?><a href="<?php echo e(route('corrections.create', ['target_type' => 'student', 'target_id' => $student->id])); ?>" class="btn btn-outline-secondary">Ajukan Koreksi</a><?php endif; ?>
                <?php if($canCreateConsultation): ?><a href="<?php echo e(route('consultations.create', ['student_id' => $student->id])); ?>" class="btn btn-outline-primary">Catat Konsultasi</a><?php endif; ?>
                <?php if($canCreateAchievement): ?><a href="<?php echo e(route('achievements.create', ['student_id' => $student->id])); ?>" class="btn btn-outline-primary">Catat Prestasi</a><?php endif; ?>
                <?php if($canCreateCase): ?><a href="<?php echo e(route('cases.create', ['student_id' => $student->id])); ?>" class="btn btn-primary">Buat Kasus</a><?php endif; ?>
            </div>
        </div>

        <?php if($isWakaSummary): ?><div class="alert alert-info">Profil ini dibatasi pada ringkasan dan kasus yang dikoordinasikan kepada Anda.</div><?php endif; ?>
        <div class="sibk-panel mb-4"><div class="sibk-panel__body p-4 d-flex align-items-center gap-3"><div class="sibk-student-avatar"><?php echo e($initials); ?></div><div><h2 class="fs-4 mb-1"><?php echo e($student->name); ?></h2><div class="text-muted small">NISN <?php echo e($student->nisn); ?> &bull; <?php echo e($currentMembership?->classroom?->name ?? 'Tanpa kelas aktif'); ?> &bull; <?php echo e($currentMembership?->academicYear?->name ?? 'Tahun ajaran tidak tersedia'); ?></div></div></div></div>

        <ul class="nav nav-pills mb-4 gap-2">
            <?php $__currentLoopData = ['ringkasan' => 'Ringkasan', 'kasus' => 'Kasus dan Layanan', 'etatib' => 'Data e-Tatib']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><li class="nav-item"><a class="nav-link <?php echo e($activeTab === $key ? 'active' : ''); ?>" href="<?php echo e(route('students.show', ['student' => $student, 'tab' => $key])); ?>"><?php echo e($label); ?></a></li><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
            <?php if($canViewConsultations): ?><li class="nav-item"><a class="nav-link <?php echo e($activeTab === 'konsultasi' ? 'active' : ''); ?>" href="<?php echo e(route('students.show', ['student' => $student, 'tab' => 'konsultasi'])); ?>">Konsultasi dan Tindak Lanjut</a></li><?php endif; ?>
            <li class="nav-item"><a class="nav-link <?php echo e($activeTab === 'prestasi' ? 'active' : ''); ?>" href="<?php echo e(route('students.show', ['student' => $student, 'tab' => 'prestasi'])); ?>">Prestasi</a></li>
        </ul>

        <div class="row g-3 mb-4">
            <?php $__currentLoopData = [
                ['Kasus Aktif', $stats['active_cases'], 'primary', 'Dalam kewenangan'],
                ['Poin e-Tatib', $stats['points'], 'warning', 'Data yang diizinkan'],
                ['Tindak Lanjut', $stats['follow_ups'], 'info', 'Terjadwal'],
                ['Prestasi', $stats['achievements'], 'secondary', 'Sesuai kewenangan'],
            ]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as [$label, $value, $tone, $sub]): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                <div class="col-6 col-xl-3"><div class="sibk-stat-card p-2 p-sm-3 border bg-white h-100"><div class="text-muted small text-truncate"><?php echo e($label); ?></div><div class="fs-5 fs-sm-4 fw-bold text-<?php echo e($tone); ?> my-1"><?php echo e($value); ?></div><div class="small text-muted" style="font-size: 0.75rem; line-height: 1.2;"><?php echo e($sub); ?></div></div></div>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
        </div>

        <?php if($activeTab === 'ringkasan'): ?>
            <div class="row g-4">
                <div class="col-12 col-lg-7"><div class="sibk-panel h-100"><div class="sibk-panel__header p-4 pb-0"><h2 class="sibk-panel__title">Ringkasan Operasional</h2></div><div class="sibk-panel__body p-4">
                    <p><span class="text-muted small d-block">Kasus terakhir</span><?php if($cases->first()): ?><a href="<?php echo e(route('cases.show', $cases->first())); ?>" class="fw-semibold"><?php echo e($cases->first()->registration_number); ?> &bull; <?php echo e($cases->first()->status->label); ?></a><?php else: ?> Belum ada <?php endif; ?></p>
                    <p><span class="text-muted small d-block">Tindak lanjut berikutnya</span><?php $next = $cases->flatMap->followUps->filter(fn ($item) => $item->planned_date->gte(today()) && $item->status?->code !== 'dibatalkan')->sortBy('planned_date')->first(); ?> <?php echo e($next?->planned_date?->locale('id')->translatedFormat('d F Y') ?? 'Belum ada'); ?></p>
                    <div><span class="text-muted small d-block mb-2">Histori kelas</span><?php $__empty_1 = true; $__currentLoopData = $memberships; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $membership): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="border-bottom py-2"><strong><?php echo e($membership->classroom->name); ?></strong><span class="small text-muted d-block"><?php echo e($membership->academicYear->name); ?> &bull; <?php echo e($membership->effective_from->format('d-m-Y')); ?> s.d. <?php echo e($membership->effective_until?->format('d-m-Y') ?? 'sekarang'); ?></span></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?> Belum ada histori kelas. <?php endif; ?></div>
                </div></div></div>
                <div class="col-12 col-lg-5"><div class="sibk-panel h-100"><div class="sibk-panel__header p-4 pb-0"><h2 class="sibk-panel__title">Aktivitas Terbaru</h2></div><div class="sibk-panel__body p-4"><?php $__empty_1 = true; $__currentLoopData = $recentActivities; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $activity): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="border-bottom py-2"><strong><?php echo e($activity['date']?->locale('id')->translatedFormat('d M Y')); ?></strong><span class="text-muted d-block"><?php echo e($activity['label']); ?></span></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="text-muted mb-0">Belum ada aktivitas.</p><?php endif; ?></div></div></div>
            </div>
        <?php elseif($activeTab === 'kasus'): ?>
            <div class="table-responsive"><table class="table sibk-table mb-0"><thead><tr><th>No.</th><th>Tanggal</th><th>Bidang</th><th>Sumber</th><th>Status</th><th>Guru BK</th><th></th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $cases; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $case): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td class="fw-bold text-primary"><?php echo e($case->registration_number); ?></td><td><?php echo e($case->service_date->locale('id')->translatedFormat('d M Y')); ?></td><td><?php echo e($case->serviceField->label); ?></td><td><?php echo e($case->source->label); ?></td><td><?php echo e($case->status->label); ?></td><td><?php echo e($case->assignments->sortByDesc('effective_from')->first()?->teacher?->name ?? '—'); ?></td><td><a href="<?php echo e(route('cases.show', $case)); ?>">Buka</a></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7" class="text-center text-muted py-4">Belum ada riwayat kasus yang dapat diakses.</td></tr><?php endif; ?></tbody></table></div>
        <?php elseif($activeTab === 'etatib'): ?>
            <div class="table-responsive"><table class="table sibk-table mb-0"><thead><tr><th>Waktu</th><th>Pelanggaran</th><th>Kategori</th><th>Poin</th><th>Status Sumber</th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $etatibRecords; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $record): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><?php echo e($record->occurred_at->locale('id')->translatedFormat('d M Y H:i')); ?></td><td><?php echo e($record->violation_type); ?></td><td><?php echo e($record->category); ?></td><td class="fw-bold text-danger">+<?php echo e($record->points); ?></td><td><?php echo e($record->source_status ?: '—'); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="5" class="text-center text-muted py-4">Tidak ada data e-Tatib yang dapat ditampilkan.</td></tr><?php endif; ?></tbody></table></div>
        <?php elseif($activeTab === 'konsultasi' && $canViewConsultations): ?>
            <div class="table-responsive"><table class="table sibk-table mb-0"><thead><tr><th>No. Sesi</th><th>Tanggal</th><th>Jenis</th><th>Kasus</th><th>Status</th><th>Ringkasan Umum</th><th></th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $consultations; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $session): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td class="fw-bold text-primary"><?php echo e($session->registration_number); ?></td><td><?php echo e($session->session_date->locale('id')->translatedFormat('d M Y')); ?></td><td><?php echo e($session->serviceField->label); ?></td><td><?php echo e($session->case?->registration_number ?? '—'); ?></td><td><?php echo e($session->status->label); ?></td><td><?php echo e(\Illuminate\Support\Str::limit($session->general_summary ?: '—', 100)); ?></td><td><a href="<?php echo e(route('consultations.show', $session)); ?>">Buka</a></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7" class="text-center text-muted py-4">Belum ada konsultasi yang dapat diakses.</td></tr><?php endif; ?></tbody></table></div>
        <?php else: ?>
            <?php if($canCreateAchievement): ?><div class="d-flex justify-content-end mb-3"><a href="<?php echo e(route('achievements.create', ['student_id' => $student->id])); ?>" class="btn btn-primary">Catat Prestasi</a></div><?php endif; ?>
            <div class="table-responsive"><table class="table sibk-table mb-0"><thead><tr><th>Tanggal</th><th>Kegiatan</th><th>Jenis / Tingkat</th><th>Hasil</th><th>Status</th><th>Pencatat</th><th></th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $achievements; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $achievement): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><?php $tone = match($achievement->verificationStatus->code) {'terverifikasi' => 'success', 'ditolak' => 'danger', default => 'warning'}; ?><tr><td><?php echo e($achievement->achievement_date->locale('id')->translatedFormat('d M Y')); ?></td><td><?php echo e($achievement->activity_name); ?><span class="small text-muted d-block"><?php echo e($achievement->organizer); ?></span></td><td><?php echo e($achievement->type->label); ?> / <?php echo e($achievement->level->label); ?></td><td><?php echo e($achievement->result); ?></td><td><span class="badge text-bg-<?php echo e($tone); ?>"><?php echo e($achievement->verificationStatus->label); ?></span></td><td><?php echo e($achievement->recorder->name); ?></td><td><a href="<?php echo e(route('achievements.show', $achievement)); ?>">Buka</a></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7" class="text-center text-muted py-5">Belum ada prestasi yang dapat ditampilkan.</td></tr><?php endif; ?></tbody></table></div>
        <?php endif; ?>
    </div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app-2', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\Tugas\pepe g\smt 2\pk\sibk\sibk\resources\views\pages\students\show.blade.php ENDPATH**/ ?>