<?php $__env->startSection('page-title', 'Riwayat Perubahan - Ruang BK'); ?>
<?php $__env->startSection('body'); ?>
<div class="sibk-dashboard" data-page-id="PG-406">
    <div class="sibk-page-header mb-4"><div class="sibk-page-header__copy"><h1>Riwayat Perubahan</h1><p>Jejak audit append-only sesuai fungsi dan kewenangan pengguna.</p></div></div>
    <div class="sibk-panel mb-4"><div class="sibk-panel__body p-4"><form class="row g-3 align-items-end" action="<?php echo e(route('history.index')); ?>" method="GET"><div class="col-md-5"><label for="search" class="form-label">Cari</label><input class="form-control" id="search" name="search" value="<?php echo e(request('search')); ?>" placeholder="Tindakan, ringkasan, atau pengguna"></div><div class="col-md-3"><label for="action_type" class="form-label">Jenis Perubahan</label><input class="form-control" id="action_type" name="action_type" value="<?php echo e(request('action_type')); ?>" placeholder="Contoh: correction."></div><div class="col-md-2"><label for="period" class="form-label">Periode</label><select class="form-select" id="period" name="period"><option value="">Semua</option><option value="today" <?php if(request('period') === 'today'): echo 'selected'; endif; ?>>Hari ini</option><option value="week" <?php if(request('period') === 'week'): echo 'selected'; endif; ?>>7 hari</option><option value="month" <?php if(request('period') === 'month'): echo 'selected'; endif; ?>>30 hari</option></select></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">Filter</button></div></form></div></div>
    <div class="table-responsive"><table class="table sibk-table mb-0"><thead><tr><th>Waktu</th><th>Pengguna</th><th>Objek</th><th>Tindakan</th><th>Ringkasan</th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $historyLogs; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $log): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td class="text-muted"><?php echo e($log->created_at->locale('id')->translatedFormat('d M Y H:i')); ?></td><td class="fw-semibold"><?php echo e($log->actor?->name ?? 'Sistem'); ?></td><td><?php echo e(class_basename($log->auditable_type)); ?> #<?php echo e($log->auditable_id); ?></td><td><span class="badge bg-light text-dark border"><?php echo e($log->action); ?></span></td><td><?php echo e($log->summary); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="5" class="text-center py-4 text-muted">Belum ada riwayat perubahan yang dapat ditampilkan.</td></tr><?php endif; ?></tbody></table></div><?php if($historyLogs->hasPages()): ?><div class="mt-3"><?php echo e($historyLogs->links()); ?></div><?php endif; ?>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app-2', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\Tugas\pepe g\smt 2\pk\sibk\sibk\resources\views\pages\history\index.blade.php ENDPATH**/ ?>