<?php $__env->startSection('page-title', 'Detail Prestasi - Ruang BK'); ?>

<?php $__env->startSection('body'); ?>
<?php $tone = match($achievement->verificationStatus->code) {'terverifikasi' => 'success', 'ditolak' => 'danger', default => 'warning'}; ?>
<div class="sibk-dashboard">
    <div class="sibk-page-header d-flex flex-wrap justify-content-between gap-3 mb-4"><div class="sibk-page-header__copy"><a href="<?php echo e(route('achievements.index')); ?>" class="text-decoration-none small">&larr; Daftar Prestasi</a><h1>Detail Prestasi</h1><p>Data, bukti metadata, dan hasil verifikasi prestasi.</p></div><div class="d-flex gap-2"><?php if(auth()->user()?->hasRole('guru_bk') && $achievement->verificationStatus->code === 'terverifikasi'): ?><a href="<?php echo e(route('corrections.create', ['target_type' => 'achievement', 'target_id' => $achievement->id])); ?>" class="btn btn-outline-secondary">Ajukan Koreksi</a><?php endif; ?> <?php if($canUpdateAchievement): ?><a href="<?php echo e(route('achievements.edit', $achievement)); ?>" class="btn btn-primary">Edit Prestasi</a><?php endif; ?></div></div>
    <div class="row g-4"><div class="col-12 col-lg-8"><div class="sibk-panel h-100"><div class="sibk-panel__body p-4"><div class="d-flex flex-wrap justify-content-between gap-3 mb-4"><div><h2 class="fs-4 mb-1"><?php echo e($achievement->activity_name); ?></h2><p class="text-muted mb-0"><?php echo e($achievement->student->name); ?> — <?php echo e($achievement->student->nisn); ?></p></div><span class="badge text-bg-<?php echo e($tone); ?> align-self-start"><?php echo e($achievement->verificationStatus->label); ?></span></div><dl class="row mb-0"><dt class="col-sm-4">Jenis / Tingkat</dt><dd class="col-sm-8"><?php echo e($achievement->type->label); ?> / <?php echo e($achievement->level->label); ?></dd><dt class="col-sm-4">Penyelenggara</dt><dd class="col-sm-8"><?php echo e($achievement->organizer); ?></dd><dt class="col-sm-4">Tanggal</dt><dd class="col-sm-8"><?php echo e($achievement->achievement_date->locale('id')->translatedFormat('d F Y')); ?></dd><dt class="col-sm-4">Hasil</dt><dd class="col-sm-8"><?php echo e($achievement->result); ?></dd><dt class="col-sm-4">Referensi Bukti</dt><dd class="col-sm-8"><?php if($evidenceUrl): ?><a href="<?php echo e($evidenceUrl); ?>" target="_blank" rel="noopener noreferrer"><?php echo e($achievement->evidence_reference); ?></a><?php else: ?><?php echo e($achievement->evidence_reference); ?><?php endif; ?></dd><dt class="col-sm-4">Keterangan Bukti</dt><dd class="col-sm-8"><?php echo e($achievement->evidence_description ?: '—'); ?></dd><dt class="col-sm-4">Catatan</dt><dd class="col-sm-8"><?php echo e($achievement->notes ?: '—'); ?></dd></dl></div></div></div>
        <div class="col-12 col-lg-4"><div class="sibk-panel mb-4"><div class="sibk-panel__body p-4"><h2 class="fs-5">Pemeriksaan</h2><p class="mb-1"><span class="text-muted small d-block">Pencatat</span><?php echo e($achievement->recorder->name); ?></p><p class="mb-1"><span class="text-muted small d-block">Pemeriksa</span><?php echo e($achievement->reviewer?->name ?? 'Belum diperiksa'); ?></p><p class="mb-1"><span class="text-muted small d-block">Waktu pemeriksaan</span><?php echo e($achievement->reviewed_at?->locale('id')->translatedFormat('d M Y H.i') ?? '—'); ?></p><p class="mb-0"><span class="text-muted small d-block">Catatan pemeriksaan</span><?php echo e($achievement->verification_notes ?: '—'); ?></p></div></div>
        <?php if($canVerifyAchievement): ?><div class="sibk-panel"><div class="sibk-panel__body p-4"><h2 class="fs-5">Verifikasi Prestasi</h2><form action="<?php echo e(route('achievements.verify', $achievement)); ?>" method="POST"><?php echo csrf_field(); ?><div class="mb-3"><label for="decision" class="form-label">Keputusan</label><select id="decision" name="decision" class="form-select" required><option value="">Pilih keputusan</option><option value="terverifikasi" <?php if(old('decision') === 'terverifikasi'): echo 'selected'; endif; ?>>Terverifikasi</option><option value="ditolak" <?php if(old('decision') === 'ditolak'): echo 'selected'; endif; ?>>Ditolak</option></select></div><div class="mb-3"><label for="verification_notes" class="form-label">Catatan pemeriksaan</label><textarea id="verification_notes" name="verification_notes" class="form-control" rows="3"><?php echo e(old('verification_notes')); ?></textarea><div class="form-text">Wajib diisi bila prestasi ditolak.</div></div><button class="btn btn-primary w-100">Simpan Keputusan</button></form></div></div><?php endif; ?></div></div>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app-2', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\Tugas\pepe g\smt 2\pk\sibk\sibk\resources\views\pages\achievements\show.blade.php ENDPATH**/ ?>