<?php $__env->startSection('page-title', 'Pratinjau ' . $report['title'] . ' - Ruang BK'); ?>

<?php $__env->startSection('body'); ?>
<div class="sibk-dashboard sibk-report-preview-page" data-page-id="PG-302">
    <div class="sibk-print-header"><p class="sibk-print-header__instansi">Pemerintah Provinsi Jawa Timur · Dinas Pendidikan</p><h1 class="sibk-print-header__sekolah">SMK Negeri 1 Surabaya</h1><p class="sibk-print-header__alamat">Jl. SMEA No. 4, Wonokromo, Surabaya, Jawa Timur 60243</p><h2 class="sibk-print-header__judul">Laporan Bimbingan dan Konseling: <?php echo e($report['title']); ?></h2><p class="sibk-print-header__periode">Periode <?php echo e($report['period_start']->locale('id')->translatedFormat('d M Y')); ?>–<?php echo e($report['period_end']->locale('id')->translatedFormat('d M Y')); ?> · <?php echo e($report['academic_year']?->name ?? 'Tanpa tahun ajaran'); ?></p></div>
    <div class="sibk-page-header mb-4 no-print"><div class="d-flex align-items-center gap-2 mb-2"><a href="<?php echo e(route('reports.index')); ?>" class="sibk-back-link text-decoration-none text-muted small fw-semibold">← Pusat Laporan</a></div><div class="sibk-page-header__copy"><h1>Pratinjau Laporan</h1><p><?php echo e($report['title']); ?> — <span class="text-muted"><?php echo e($report['description']); ?></span></p></div></div>

    <div class="sibk-panel mb-4 sibk-filter-panel no-print"><div class="sibk-panel__body p-4"><form class="row g-3 align-items-end" action="<?php echo e(route('reports.preview')); ?>" method="GET"><input type="hidden" name="type" value="<?php echo e($report['id']); ?>">
        <?php if(in_array('period', $report['filter_keys'], true)): ?>
            <div class="col-12 col-sm-6 col-lg-2"><label class="form-label" for="academic_year_id">Tahun Ajaran</label><select class="form-select" id="academic_year_id" name="academic_year_id"><?php $__currentLoopData = $report['filter_options']['academic_years']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $year): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($year->id); ?>" <?php if((int) $report['filters']['academic_year_id'] === $year->id): echo 'selected'; endif; ?>><?php echo e($year->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
            <div class="col-12 col-sm-6 col-lg-2"><label class="form-label" for="date_start">Tanggal Awal</label><input class="form-control" id="date_start" name="date_start" type="date" value="<?php echo e($report['filters']['date_start']); ?>"></div>
            <div class="col-12 col-sm-6 col-lg-2"><label class="form-label" for="date_end">Tanggal Akhir</label><input class="form-control" id="date_end" name="date_end" type="date" value="<?php echo e($report['filters']['date_end']); ?>"></div>
        <?php endif; ?>
        <?php if(in_array('classroom', $report['filter_keys'], true)): ?><div class="col-12 col-sm-6 col-lg-2"><label class="form-label" for="classroom_id">Kelas</label><select class="form-select" id="classroom_id" name="classroom_id"><option value="">Semua kelas</option><?php $__currentLoopData = $report['filter_options']['classrooms']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $classroom): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($classroom->id); ?>" <?php if((int) ($report['filters']['classroom_id'] ?? 0) === $classroom->id): echo 'selected'; endif; ?>><?php echo e($classroom->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><?php endif; ?>
        <?php if(in_array('student', $report['filter_keys'], true)): ?><div class="col-12 col-sm-6 col-lg-2"><label class="form-label" for="student_id">Murid</label><select class="form-select" id="student_id" name="student_id"><option value="">Semua murid</option><?php $__currentLoopData = $report['filter_options']['students']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $student): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($student['id']); ?>" <?php if((int) ($report['filters']['student_id'] ?? 0) === $student['id']): echo 'selected'; endif; ?>><?php echo e($student['label']); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><?php endif; ?>
        <?php if(in_array('category', $report['filter_keys'], true)): ?><div class="col-12 col-sm-6 col-lg-2"><label class="form-label" for="category">Kategori</label><select class="form-select" id="category" name="category"><option value="">Semua kategori</option><?php $__currentLoopData = $report['filter_options']['categories']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $category): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($category); ?>" <?php if(($report['filters']['category'] ?? '') === $category): echo 'selected'; endif; ?>><?php echo e($category); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><?php endif; ?>
        <?php if(in_array('service_field', $report['filter_keys'], true)): ?><div class="col-12 col-sm-6 col-lg-2"><label class="form-label" for="service_field_id">Bidang</label><select class="form-select" id="service_field_id" name="service_field_id"><option value="">Semua bidang</option><?php $__currentLoopData = $report['filter_options']['service_fields']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $field): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($field->id); ?>" <?php if((int) ($report['filters']['service_field_id'] ?? 0) === $field->id): echo 'selected'; endif; ?>><?php echo e($field->label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><?php endif; ?>
        <?php if(in_array('status', $report['filter_keys'], true)): ?><div class="col-12 col-sm-6 col-lg-2"><label class="form-label" for="status_id">Status</label><select class="form-select" id="status_id" name="status_id"><option value="">Semua status</option><?php $__currentLoopData = $report['filter_options']['statuses']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $status): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($status->id); ?>" <?php if((int) ($report['filters']['status_id'] ?? 0) === $status->id): echo 'selected'; endif; ?>><?php echo e($status->label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><?php endif; ?>
        <?php if(in_array('achievement_type', $report['filter_keys'], true)): ?><div class="col-12 col-sm-6 col-lg-2"><label class="form-label" for="achievement_type_id">Jenis Prestasi</label><select class="form-select" id="achievement_type_id" name="achievement_type_id"><option value="">Semua jenis</option><?php $__currentLoopData = $report['filter_options']['achievement_types']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $type): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($type->id); ?>" <?php if((int) ($report['filters']['achievement_type_id'] ?? 0) === $type->id): echo 'selected'; endif; ?>><?php echo e($type->label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><?php endif; ?>
        <?php if(in_array('achievement_level', $report['filter_keys'], true)): ?><div class="col-12 col-sm-6 col-lg-2"><label class="form-label" for="achievement_level_id">Tingkat Prestasi</label><select class="form-select" id="achievement_level_id" name="achievement_level_id"><option value="">Semua tingkat</option><?php $__currentLoopData = $report['filter_options']['achievement_levels']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $level): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($level->id); ?>" <?php if((int) ($report['filters']['achievement_level_id'] ?? 0) === $level->id): echo 'selected'; endif; ?>><?php echo e($level->label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><?php endif; ?>
        <?php if(in_array('counselor', $report['filter_keys'], true) && $report['filter_options']['counselors']->isNotEmpty()): ?><div class="col-12 col-sm-6 col-lg-2"><label class="form-label" for="counselor_id">Guru BK</label><select class="form-select" id="counselor_id" name="counselor_id"><option value="">Semua Guru BK</option><?php $__currentLoopData = $report['filter_options']['counselors']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $counselor): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($counselor->id); ?>" <?php if((int) ($report['filters']['counselor_id'] ?? 0) === $counselor->id): echo 'selected'; endif; ?>><?php echo e($counselor->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><?php endif; ?>
        <?php if(in_array('minimum_points', $report['filter_keys'], true)): ?><div class="col-12 col-sm-6 col-lg-2"><label class="form-label" for="minimum_points">Ambang Poin</label><input class="form-control" id="minimum_points" name="minimum_points" type="number" min="0" value="<?php echo e($report['filters']['minimum_points'] ?? ''); ?>" placeholder="0"></div><?php endif; ?>
        <div class="col-12 col-sm-6 col-lg-2 ms-auto"><button type="submit" class="btn btn-primary w-100">Terapkan</button></div>
    </form></div></div>

    <div class="row g-3 mb-4 sibk-report-kpi-row"><?php $__currentLoopData = ['total' => 'primary', 'active' => 'warning', 'completed' => 'success']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key => $tone): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="col-12 col-md-4"><article class="sibk-stat-card sibk-tone--<?php echo e($tone); ?> p-3"><h2 class="sibk-stat-card__label text-muted small fw-semibold mb-1"><?php echo e($report['stats'][$key]['label']); ?></h2><div class="sibk-stat-card__value fs-2 fw-bold text-dark"><?php echo e($report['stats'][$key]['value']); ?></div><span class="sibk-stat-meta text-muted small"><?php echo e($report['stats'][$key]['sub']); ?></span></article></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>

    <div class="table-responsive mb-4"><table class="table sibk-table align-middle mb-0"><thead><tr><?php $__currentLoopData = $report['columns']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $column): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><th scope="col"><?php echo e($column); ?></th><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $report['rows']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $row): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><?php $__currentLoopData = $row['cells']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $cell): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><td><?php if($cell['badge_tone']): ?><span class="sibk-badge sibk-badge--<?php echo e($cell['badge_tone']); ?>"><?php echo e($cell['value']); ?></span><?php else: ?><?php echo e($cell['value']); ?><?php endif; ?></td><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="<?php echo e(count($report['columns'])); ?>" class="text-center py-5 text-muted">Tidak ada data untuk filter dan kewenangan yang dipilih.</td></tr><?php endif; ?></tbody></table></div><?php if($report['rows']->hasPages()): ?><div class="mb-4 no-print"><?php echo e($report['rows']->links()); ?></div><?php endif; ?>

    <div class="d-flex flex-wrap justify-content-end gap-3 no-print mb-4"><button type="button" class="btn btn-outline-secondary" data-print-report>Cetak Laporan</button><a class="btn btn-primary" href="<?php echo e(route('reports.export', [...request()->except('page'), 'type' => $report['id'], 'format' => 'csv'])); ?>">Unduh CSV</a><button class="btn btn-outline-secondary" type="button" disabled title="Menunggu keputusan DEP-07">XLSX belum tersedia</button><button class="btn btn-outline-secondary" type="button" disabled title="Gunakan Cetak Laporan untuk menyimpan PDF">PDF server belum tersedia</button></div>
    <div class="sibk-print-footer"><div class="sibk-print-footer__grid"><div class="sibk-print-footer__col"><p class="sibk-print-footer__role">Mengetahui,<br>Koordinator Bimbingan dan Konseling</p><p class="sibk-print-footer__name">(........................................)</p></div><div class="sibk-print-footer__col"><p class="sibk-print-footer__role">Surabaya, <?php echo e($report['generated_at']->locale('id')->translatedFormat('d F Y')); ?><br>Dicetak oleh <?php echo e($report['generated_by']); ?></p><p class="sibk-print-footer__name">(........................................)</p></div></div></div>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app-2', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\cadangan\Tugas Kuliah\PGG\Sesmter 2\PK\Website BK\sibk\resources\views/pages/reports/preview.blade.php ENDPATH**/ ?>