<?php $__env->startSection('page-title', 'Koreksi Data - Ruang BK'); ?>
<?php $__env->startSection('body'); ?>
<div class="sibk-dashboard" data-page-id="PG-404">
    <?php if(session('success')): ?><div class="alert alert-success"><?php echo e(session('success')); ?></div><?php endif; ?>
    <div class="sibk-page-header d-flex flex-column flex-md-row align-items-md-center justify-content-between gap-3 mb-4"><div class="sibk-page-header__copy"><h1>Koreksi Data</h1><p>Daftar pengajuan koreksi data operasional dan master sesuai kewenangan.</p></div><?php if($canCreateCorrection): ?><a href="<?php echo e(route('corrections.create')); ?>" class="btn btn-primary">+ Ajukan Koreksi</a><?php endif; ?></div>
    <div class="sibk-panel mb-4"><div class="sibk-panel__body p-4"><form class="row g-3 align-items-end" action="<?php echo e(route('corrections.index')); ?>" method="GET">
        <div class="col-12 col-md-4"><label for="search" class="form-label">Cari</label><input type="text" class="form-control" id="search" name="search" value="<?php echo e(request('search')); ?>" placeholder="Nomor, objek, atribut, atau pengaju"></div>
        <div class="col-12 col-md-3"><label for="correction_type" class="form-label">Jenis Data</label><select class="form-select" id="correction_type" name="correction_type"><option value="">Semua jenis</option><option value="operational" <?php if(request('correction_type') === 'operational'): echo 'selected'; endif; ?>>Operasional</option><option value="master" <?php if(request('correction_type') === 'master'): echo 'selected'; endif; ?>>Master</option></select></div>
        <div class="col-12 col-md-3"><label for="status_id" class="form-label">Status</label><select class="form-select" id="status_id" name="status_id"><option value="">Semua status</option><?php $__currentLoopData = $statuses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $status): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($status->id); ?>" <?php if((string) request('status_id') === (string) $status->id): echo 'selected'; endif; ?>><?php echo e($status->label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-12 col-md-2"><button type="submit" class="btn btn-outline-primary w-100">Filter</button></div>
    </form></div></div>
    <div class="table-responsive"><table class="table sibk-table mb-0"><thead><tr><th>No. Koreksi</th><th>Objek</th><th>Atribut</th><th>Pengaju</th><th>Jenis</th><th>Status</th><th>Tanggal</th><th></th></tr></thead><tbody>
    <?php $__empty_1 = true; $__currentLoopData = $corrections; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td class="fw-bold text-primary"><?php echo e($item->registration_number); ?></td><td class="fw-semibold"><?php echo e($item->target_label); ?></td><td><?php echo e($item->field_label); ?></td><td><?php echo e($item->requester->name); ?></td><td><span class="badge bg-light text-dark border"><?php echo e($item->correction_type === 'master' ? 'Master' : 'Operasional'); ?></span></td><td><span class="sibk-badge sibk-badge--<?php echo e(in_array($item->status->code, ['disetujui', 'selesai'], true) ? 'success' : ($item->status->code === 'ditolak' ? 'danger' : 'warning')); ?>"><?php echo e($item->status->label); ?></span></td><td class="text-muted"><?php echo e($item->created_at->locale('id')->translatedFormat('d M Y')); ?></td><td><a href="<?php echo e(route('corrections.show', $item)); ?>" class="fw-bold text-decoration-none">Buka</a></td></tr>
    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="8" class="text-center py-4 text-muted">Belum ada pengajuan koreksi data.</td></tr><?php endif; ?>
    </tbody></table></div><?php if($corrections->hasPages()): ?><div class="mt-3"><?php echo e($corrections->links()); ?></div><?php endif; ?>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app-2', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\Tugas\pepe g\smt 2\pk\sibk\sibk\resources\views\pages\corrections\index.blade.php ENDPATH**/ ?>